vich_uploader:
    db_driver: orm

    mappings:
        uploadfile:
            directory_namer: pasaia.vich.directory.namer
            uri_prefix:         /uploads
            upload_destination: '%kernel.root_dir%/../public/uploads'
            namer:  Vich\UploaderBundle\Naming\SmartUniqueNamer
            #            namer:              vich_uploader.namer_uniqid # will rename your uploaded files using a uniqueid for the name and keep the extension
            #            namer:              vich_uploader.namer_origname # will rename your uploaded files using a uniqueid as the prefix of the filename and keeping the original name and extension
            inject_on_load:     true # should the file be injected into the uploadable entity when it is loaded from the data store.
            delete_on_update:   true # should the file be deleted when a new file is uploaded
            delete_on_remove:   true # should the file be deleted when the entity is removed

        zerrenda_employee:
            #            directory_namer: app.document.directory_namer
            #            directory_namer: App\Service\VichUploadBundleDirectoryNamer
            uri_prefix:         /uploads
            upload_destination: '%kernel.root_dir%/../public/uploads'
            #            namer:              vich_uploader.namer_uniqid # will rename your uploaded files using a uniqueid for the name and keep the extension
            #            namer:              vich_uploader.namer_origname # will rename your uploaded files using a uniqueid as the prefix of the filename and keeping the original name and extension
            inject_on_load:     true # should the file be injected into the uploadable entity when it is loaded from the data store.
            delete_on_update:   true # should the file be deleted when a new file is uploaded
            delete_on_remove:   true # should the file be deleted when the entity is removed
