version:  '3.7'
services:
    db:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        restart: on-failure
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
        volumes:
        - ./docker/data:/var/lib/mysql

    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                - DOCKER_TIMEZONE=${DOCKER_TIMEZONE}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
        restart: on-failure
        depends_on:
          - db
          - redis
        volumes:
            - '.:/usr/src/app'
            - './docker/php/conf/.zsh_history:/home/www-data/.zsh_history:rw'
            - './docker/php/conf/php.ini:/usr/local/etc/php/php.ini:ro'

    nginx:
        image: nginx:1.15.3-alpine
        restart: on-failure
        volumes:
        - ./public/:/usr/src/app
        - ordezkatu_uploads:/usr/src/app/public/uploads/
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "80:80"
        depends_on:
            - app

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
        - ./docker/data-redis:/data

volumes:
    ordezkatu_uploads:

networks:
    default:
        ipam:
            config:
                - subnet: 172.177.0.0/16