version:  '3.7'
services:
  db:
    command: ["--default-authentication-plugin=mysql_native_password"]
    container_name: ordezkatu_db
    environment:
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
    image: mysql:8.0
    networks:
      - ordezkatu_net
    ports:
      - '3306:3306'
    restart: on-failure
    volumes:
      - ordezkatu_mysql:/var/lib/mysql

  app:
    container_name: ordezkatu_app
    depends_on:
      - db
      - redis
    image: ikerib/ordezkatu_app:0.1
    networks:
      - ordezkatu_net
    restart: on-failure
    working_dir: /usr/src/app

  nginx:
    depends_on:
      - app
    image: ikerib/ordezkatu_nginx:0.1
    networks:
      - ordezkatu_net
    ports:
      - 80:80
      - 443:443
    restart: on-failure

  redis:
    container_name: ordezkatu_redis
    image: redis:alpine
    networks:
      - ordezkatu_net
    ports:
      - "6380:637"
    restart: on-failure
    volumes:
      - ordezkatu_redis:/data

volumes:
  ordezkatu_mysql:
  ordezkatu_redis:
  ordezkatu_app:

networks:
  ordezkatu_net:
    ipam:
      config:
        - subnet: 172.179.0.0/16
