version: '3.4'

services:
  app:
      ports:
      - 8080:80
      environment:
          - APACHE_DOCUMENT_ROOT=/var/www/html/app/public
      build:
          context: .
      volumes:
      - .:/var/www/html/
      - ./config/vhost.conf:/etc/apache/sites-available/000-default.conf
